service: awwwserverless
app: awwserverless
org: ed42311
frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript
  # - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# graphql:
#   handler: handler.graphqlHandler
#   events:
#   - http:
#       path: graphql
#       method: post
#       cors: true
